#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ShimmerQs.Resource", IsApplication=true)]

namespace ShimmerQs
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int angle = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int auto_start = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int base_alpha = 2130771969;
			
			// aapt resource value: 0x7f010007
			public const int dropoff = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int duration = 2130771970;
			
			// aapt resource value: 0x7f010009
			public const int fixed_height = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int fixed_width = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int intensity = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public const int relative_height = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int relative_width = 2130771979;
			
			// aapt resource value: 0x7f010003
			public const int repeat_count = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int repeat_delay = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int repeat_mode = 2130771973;
			
			// aapt resource value: 0x7f01000d
			public const int shape = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int tilt = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int preset_button_background = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int preset_button_background_selected = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fb_logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int cw_0 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int cw_180 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int cw_270 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int cw_90 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int linear = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int preset_button0 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int preset_button1 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int preset_button2 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int preset_button3 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int preset_button4 = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int radial = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int restart = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int reverse = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int settings_container = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int shimmer_view_container = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int thin_white = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int thin_white_large = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int thin_white_small = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int thin_white_small_button = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ShimmerFrameLayout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 6
			public const int ShimmerFrameLayout_angle = 6;
			
			// aapt resource value: 0
			public const int ShimmerFrameLayout_auto_start = 0;
			
			// aapt resource value: 1
			public const int ShimmerFrameLayout_base_alpha = 1;
			
			// aapt resource value: 7
			public const int ShimmerFrameLayout_dropoff = 7;
			
			// aapt resource value: 2
			public const int ShimmerFrameLayout_duration = 2;
			
			// aapt resource value: 9
			public const int ShimmerFrameLayout_fixed_height = 9;
			
			// aapt resource value: 8
			public const int ShimmerFrameLayout_fixed_width = 8;
			
			// aapt resource value: 10
			public const int ShimmerFrameLayout_intensity = 10;
			
			// aapt resource value: 12
			public const int ShimmerFrameLayout_relative_height = 12;
			
			// aapt resource value: 11
			public const int ShimmerFrameLayout_relative_width = 11;
			
			// aapt resource value: 3
			public const int ShimmerFrameLayout_repeat_count = 3;
			
			// aapt resource value: 4
			public const int ShimmerFrameLayout_repeat_delay = 4;
			
			// aapt resource value: 5
			public const int ShimmerFrameLayout_repeat_mode = 5;
			
			// aapt resource value: 13
			public const int ShimmerFrameLayout_shape = 13;
			
			// aapt resource value: 14
			public const int ShimmerFrameLayout_tilt = 14;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
